### ISSUE TITLE
Limit Access of Plugin to Google and DuckDuckGo Domains

### ISSUE THREAD

**Issue by newur** [szupie/tab-focus-google#2]
The plugin requests permission to [Access your data for all websites](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_access-your-data-for-all-websites).

I assume this is not required, because the plugin will/can/should not do anything on sites other than google or duckduckgo. I would prefer to only allow only access to strictly required data.

btw thanks for building this plugin. :)

**Comment by szupie** [comment]
This was a design decision. Since Google uses different top-level domains (i.e. .com, .fr, etc) for different regions, [it would be necessary to maintain a long list of whitelisted domains](https://stackoverflow.com/a/23752694/320862) to make this work for different regions. For an example, see the list of ~200 domains in the expanded permissions section for [this extension](https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1)).

As an alternative, I am currently using [a glob pattern match instead](https://github.com/szupie/tab-focus-google/blob/master/manifest.json#L9) to apply the script only to sites matching the pattern `*://www.google.*/search*`, though it does technically still require asking for access to all domains.

However, I plan on doing some more research to see how feasible it is to maintain the list. I currently have no idea how often Google updates their list of domains.

**Comment by newur** [comment]
Ya, I am aware of these long google lists and I agree that is not a perfect solution. Cumbersome for the dev side and for the end user side.

However, I would not assume that this list changes often. This would require a new country or google expanding into a new country at least, no?

It is really unfortunate that Firefox does not allow for a more flexible approach here :/

**Comment by szupie** [comment]
The add-on now uses the whitelist of Google TLDs. The [AMO listing](https://addons.mozilla.org/en-US/firefox/addon/tab-focus-google/) has been updated.

I’ve also made this available as a userscript since it’s a pretty short script: https://greasyfork.org/en/scripts/433135-tab-focus-through-google-search-results
