### ISSUE TITLE
select first result by default

### ISSUE THREAD

**Issue by AlxndrJhn** [szupie/tab-focus-google#3]
similar to https://chrome.google.com/webstore/detail/hit-tab-and-enter-on-goog/kkldgaaaafjoipnomoinnkccihdiffee

I would like the first first search result selected by default, currently the tab key needs to be pressed once.

It does not sound much, but because of this, I prefer to use Chrome (with the above mentioned extension) over firefox, as I only need to search, hit enter to go to the first result

**Comment by szupie** [comment]
That is an interesting feature suggestion. However, I do not plan on making that the default behaviour for this extension. On some Google result pages, answer snippets etc. push down the placement of the first real result below the fold, so if the first result receives focus on load, it would either have to scroll the page down to be in view, or receive focus but confusingly be offscreen. In my opinion it would be better to change focus only if it is initiated by the user.

However, if you would like that functionality for yourself, I would encourage you to install the [userscript](https://greasyfork.org/en/scripts/433135-tab-focus-through-google-search-results) version of this tool (you’ll need an extension like Greasemonkey to run userscripts, but they are much easier for end-users to customise). The following line can be added to the userscript at the end of the `init()` function ([after line 45](https://gist.github.com/szupie/d50a7b9162b42bd352a96b7bebf50b5d#file-tab-focus-results-user-js-L45)) to focus on the first result on load:
`results[0].closest('a').focus();`

Let me know if you have any questions about using userscripts. I can also create a new alternate gist for the userscript with the functionality you suggested, so that it can be installed with a click.

**Comment by AlxndrJhn** [comment]
fantastic, following your instructions I modified the user script and now it works as desired for me
